# 0. Import

In [1]:
import torch
from torch import tensor

# 1. Elementwise operations

Elementwise Operations หมายถึง ทำ Operations แยกคนละตัวเรียงตามตำแหน่ง ตัวแรกทำกับตัวแรก ตัวที่สองทำกับตัวที่สอง ... โดยอาจจะทำไปพร้อม ๆ กัน ทำขนานกันไปก็ได้

## 1.1 Basic operations

In [2]:
a = tensor([1., 2., 3., 4.])

บวก ลบ คุณ หาร ยกกำลัง กับ ตัวเลขธรรมดา ใส่ . จุด หลังตัวเลข หมายถึง ให้เป็นเลขแบบ Float จุดทศนิยม รองรับการคำนวนคณิตศาสตร์ เช่น 1. เหมือนกับ 1.0

In [3]:
a + 1

tensor([2., 3., 4., 5.])

In [4]:
2**a

tensor([ 2.,  4.,  8., 16.])

บวก ลบ คุณ หาร ยกกำลัง กับ tensor ด้วยกัน

In [5]:
b = torch.ones(4) + 1
b

tensor([2., 2., 2., 2.])

In [6]:
a - b

tensor([-1.,  0.,  1.,  2.])

In [7]:
a * b

tensor([2., 4., 6., 8.])

In [8]:
j = torch.arange(5)
j

tensor([0, 1, 2, 3, 4])

In [9]:
2**(j + 1) - j

tensor([ 2,  3,  6, 13, 28])

## 1.2 เปรียบเทียบความเร็ว

Tensor

In [10]:
a = torch.arange(10000)
%timeit a + 1  

14.6 µs ± 208 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


วน loop array

In [11]:
l = range(10000)
%timeit [i+1 for i in l] 

627 µs ± 1.34 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


tensor เร็วกว่าประมาณเกือบ 40 เท่า เนื่องจากเป็นการประมวลผลลขนาน ไม่ได้ทำทีละ item เรียงไปเรื่อย ๆ

## 1.3 Multiplication

In [12]:
c = torch.ones((3, 3))
c

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

คุณแบบปกติ จะเป็น คุณแบบ elementwise ไม่ได้คูณแบบ matrix

In [13]:
c * c     

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

คูณ matrix

In [14]:
c.matmul(c)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

## 1.4 Comparison Operations

Operation เปรียบเทียบ ก็ elementwise

In [15]:
a = tensor([1, 2, 3, 4])
b = tensor([4, 2, 2, 4])

1 คือ True, 0 คือ False

In [16]:
a == b

tensor([0, 1, 0, 1], dtype=torch.uint8)

In [17]:
a > b

tensor([0, 0, 1, 0], dtype=torch.uint8)

## 1.5 Transcendental functions

ฟัง์ชันคณิตศาสตร์ ก็ elementwise

In [18]:
a = torch.arange(5.)

In [19]:
torch.sin(a)

tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568])

In [20]:
torch.log(a)

tensor([  -inf, 0.0000, 0.6931, 1.0986, 1.3863])

In [21]:
torch.exp(a)

tensor([ 1.0000,  2.7183,  7.3891, 20.0855, 54.5981])

# 2. Broadcasting

ในกรณี 2 ฝั่งมีสมาชิกไม่เท่ากัน จะเกิดการ Broadcasting กระจายสมาชิกจาก 1 ให้กลายเป็นเท่ากัน ก่อนทำ Elementwise Operation

ใน Numpy, TensorFlow และ Pytorch มิติแรก 0 จะเป็น Row มิติที่สอง 1 จะเป็น Column

In [22]:
a = torch.arange(0, 40, 10).repeat(1, 1, 3).view(3, 4).t()
a

tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30]])

## 2.1 Row Broadcasting

กระจาย 1 Row เป็น 4 Row ก่อนบวก

In [23]:
b = tensor([0, 1, 2])
b

tensor([0, 1, 2])

In [24]:
a + b

tensor([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]])

## 2.2 Column Broadcasting

กระจาย 1 Column เป็น 3 Column ก่อนบวก

In [25]:
c = tensor([[0], [1], [2], [3]])
c

tensor([[0],
        [1],
        [2],
        [3]])

In [26]:
a + c

tensor([[ 0,  0,  0],
        [11, 11, 11],
        [22, 22, 22],
        [33, 33, 33]])

## 2.3 Row and Column Broadcasting 

In [27]:
d = tensor([2])
d

tensor([2])

In [28]:
a+d

tensor([[ 2,  2,  2],
        [12, 12, 12],
        [22, 22, 22],
        [32, 32, 32]])

หมายเหตุ การ Broadcasting ไม่ได้จำกัดอยู่แค่ 2 มิติ เราสามารถ Broadcast ได้ในทุก ๆ มิติ เช่น broardcast มิติที่ 4 ใน tensor 5 มิติ เป็นต้น

# 3. Dimension

In [29]:
a = torch.ones((4, 5))
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## 3.1 Indexing

ให้ Row ที่ 0 เป็น ค่า 2

*ไม่ได้ระบุมิติที่ 2 ให้ถือว่าเป็น : คือเอาทุก Column* 

In [30]:
a[0] = 2
a

tensor([[2., 2., 2., 2., 2.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

ให้ Column ที่ 1 (เริ่มต้นที่ 0) เป็น 3 

*หมายเหตุ : (เครื่องหมาย colon) แปลว่าทุกอัน ถ้าอยู่ตำแหน่งแรก แปลว่าทุก Row*

In [31]:
a[:, 1] = 3
a

tensor([[2., 3., 2., 2., 2.],
        [1., 3., 1., 1., 1.],
        [1., 3., 1., 1., 1.],
        [1., 3., 1., 1., 1.]])

ให้ Column ที่ 1 จากสุดท้าย เป็น 4

*Index ติดลบ แปลว่า นับจากท้ายสุด*

In [32]:
a[:, -1] = 4
a

tensor([[2., 3., 2., 2., 4.],
        [1., 3., 1., 1., 4.],
        [1., 3., 1., 1., 4.],
        [1., 3., 1., 1., 4.]])

## 3.2 Slicing

Slicing เลือกเอาช่วง Index ในลำดับที่ต้องการ

In [33]:
x = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

เริ่มที่ 3 ถึง 6 (ไม่รวม 6)

In [34]:
x[3:6]

tensor([3, 4, 5])

เริ่มที่ 1 ถึง 7 (ไม่รวม 7) ข้ามทีละ 2

In [35]:
x[1:7:2]

tensor([1, 3, 5])

เลือกอันดับ 2 จากสุดท้าย ถึง อันดับ 10 (ไม่รวม 10)

In [36]:
x[-2:10]

tensor([8, 9])

เลือกตั้งแต่ 5 เป็นต้นไป

In [37]:
x[5:]

tensor([5, 6, 7, 8, 9])

เลือกตั้งแต่ต้นจนถึง 5 (ไม่รวม 5)

In [38]:
x[:5]

tensor([0, 1, 2, 3, 4])

## 3.3 Reshape Dimenstion

Reshape ปรับรูปร่าง ปรับเปลี่ยนมิติของ Tensor โดยที่ไม่ได้ยุ่งกับข้อมูล

In [39]:
a = tensor([[1, 2, 3], [4, 5, 6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

Flattening ให้เป็น Vector (1 มิติ)

In [40]:
a.flatten()

tensor([1, 2, 3, 4, 5, 6])

Transpose สลับมิติ Row กับ Column

In [41]:
a.t()

tensor([[1, 4],
        [2, 5],
        [3, 6]])

Transpose แล้ว Flattening ตาม จะเห็นว่า Element เรียงตามมิติมากกว่าก่อน

In [42]:
a.t().flatten()

tensor([1, 4, 2, 5, 3, 6])

Reshaping เลือกเองว่าจะเแปลงเป็น มิติ เท่าไรคูณเท่าไร

In [43]:
a.shape

torch.Size([2, 3])

In [44]:
b = a.flatten()
b

tensor([1, 2, 3, 4, 5, 6])

แปลงเป็น 2 x 3

In [45]:
b = b.reshape((2, 3))
b

tensor([[1, 2, 3],
        [4, 5, 6]])

แปลงแบบไม่ระบุมิติ ด้วย -1

มิติ = -1 หมายถึงให้คำนวนเอา Element ที่เหลือมาใส่มิตินี้

In [46]:
a.reshape((2, -1))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [47]:
a.reshape((-1, 1))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [48]:
a.reshape((-1, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [49]:
a.reshape((-1, 3))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [50]:
a.reshape((-1, 6))

tensor([[1, 2, 3, 4, 5, 6]])

Adding a dimension เพิ่มมิติ เช่น ในการคำนวนเรียกฟังก์ชันบางอย่าง ต้องการ parameter 4 มิติ ทำให้เราต้องทำให้ tensor ของเราเป็น 4 มิติก่อนจะเรียกฟังก์ชันนั้นได้ โดยที่มิติที่สร้างขึ้นมาใหม่ ก็จะมีแค่ 1 Element นั่นเอง

In [51]:
z = tensor([1, 2, 3])
z

tensor([1, 2, 3])

1 มิติ 3 Element

In [52]:
z.shape

torch.Size([3])

จาก 1 มิติ เพิ่มมิติ Column ทำให้เป็น 2 มิติ คือ 3 Row 1 Column

In [53]:
z[:, None]

tensor([[1],
        [2],
        [3]])

In [54]:
z[:, None].shape

torch.Size([3, 1])

จาก 1 มิติ เพิ่มมิติ Row ไปด้านหน้า ทำให้เป็น 2 มิติ คือ 1 Row 3 Column

In [55]:
z[None]

tensor([[1, 2, 3]])

In [56]:
z[None].shape

torch.Size([1, 3])

ลองดูแบบ เพิ่มจาก 2 มิติ เป็น 3 มิติ ดูบ้าง

In [57]:
a = tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

เพิ่มด้านหลัง 

*เครื่องหมาย ... จุดไข่ปลา Ellipsis หมายถึง ทุกมิติที่เหลือ*

In [58]:
a[..., None]

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])

In [59]:
a[..., None].shape

torch.Size([3, 3, 1])

เพิ่มด้านหน้า

In [60]:
a[None, ...]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [61]:
a[None, ...].shape

torch.Size([1, 3, 3])

เราจะใช้ tensor.reshape และ tensor.view ในการ reshape แต่มีข้อระวังคือ เราจะได้ผลลัพธ์เป็น view ของ tensor เดิมเท่านั้น ไม่ได้ tensor ใหม่ แยกกัน ถ้าอยากให้สร้าง tensor ใหม่ ให้ต่อด้วย tensor.copy

# Credit

* http://scipy-lectures.org/intro/numpy/operations.html
* https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html
* https://course.fast.ai/videos/?lesson=8